{{ config(materialized="table") }}

select
    "Document Type"                         AS       "DOCUMENT_TYPE",
    "no_"                                     AS      "PRIMARY_KEY",
    "Sell-to Customer No_"                  AS       "CUSTOMER ID",
    "Bill-to Customer No_"                  AS       "BILL_TO_CUSTOMER_NO",
    "Bill-to Name"                          AS       "BILL_TO_NAME",
    "Bill-to Address"                       AS       "BILL_TO_ADDRESS",
    "Bill-to City"                          AS       "BILL_TO_CITY",
    "Bill-to Contact"                       AS       "BILL_TO_CONTACT",
    "Ship-to Name"                          AS       "SHIP_TO_NAME",
    "Ship-to Address"                       AS       "SHIP_TO_ADDRESS",
    "Ship-to City"                          AS       "SHIP_TO_CITY",
    "Ship-to Contact"                       AS       "SHIP_TO_CONTACT",
    "Order Date"                            AS       "ORDER_DATE",
    "Posting Date"                          AS       "POSTING_DATE",
    "Shipment Date"                         AS       "SHIPMENT_DATE",
    "Posting Description"                   AS       "POSTING_DESCRIPTION",
    "Payment Terms Code"                    AS       "PAYMENT_TERMS_CODE",
    "Due Date"                              AS       "DUE_DATE",
    "Payment Discount _"                    AS       "PAYMENT_DISCOUNT",
    "Pmt_ Discount Date"                    AS       "PMT_DISCOUNT_DATE",
    "Shipment Method Code"                  AS       "SHIPMENT_METHOD_CODE",
    "Location Code"                         AS       "LOCATION_CODE",
    "Shortcut Dimension 1 Code"             AS       "SHORTCUT_DIMENSION_CODE",
    "Customer Posting Group"                AS       "CUSTOMER_POSTING_GROUP",
    "Currency Code"                         AS       "CURRENCY_CODE",
    "Currency Factor"                       AS       "CURRENCY_FACTOR",
    "Invoice Disc_ Code"                    AS       "INVOICE_DISC_CODE",
    "Customer Disc_ Group"                  AS       "CUSTOMER_DISC_GROUP",
    "Language Code"                         AS       "LANGUAGE_CODE",
    "Salesperson Code"                      AS       "SALESPERSON_CODE",
    ship                                    AS       SHIP,
    invoice                                 AS       INVOICE,
    "VAT Registration No_"                  AS       "VAT_REGISTRATION_NO",
    "Gen_ Bus_ Posting Group"               AS       "GEN_BUS_POSTING_GROUP",
    "VAT Country_Region Code"               AS       "VAT_COUNTRY_REGION_CODE",
    "Sell-to Customer Name"                 AS       "SELL_TO_CUSTOMER_NAME",
    "Sell-to Address"                       AS       "SELL_TO_ADDRESS",
    "Sell-to City"                          AS       "SELL_TO_CITY",
    "Sell-to Contact"                       AS       "SELL_TO_CONTACT",
    "Bill-to Post Code"                     AS       "BILL_TO_POST_CODE",
    "Bill-to Country_Region Code"           AS       "BILL_TO_COUNTRY_REGION_CODE",
    "Sell-to Post Code"                     AS       "SELL_TO_POST_CODE",
    "Sell-to Country_Region Code"           AS       "SELL_TO_COUNTRY_REGION_CODE",
    "Ship-to Post Code"                     AS       "SHIP_TO_POST_CODE",
    "Ship-to Country_Region Code"           AS       "SHIP_TO_COUNTRY_REGION_CODE",
    "Document Date"                         AS       "DOCUMENT_DATE",
    "Shipping Agent Code"                   AS       "SHIPPING_AGENT_CODE",
    "Package Tracking No_"                  AS       "PACKAGE_TRACKING_NO",
    "No_ Series"                            AS       "NO_SERIES",
    "Posting No_ Series"                    AS       "POSTING_SERIES",
    "Shipping No_ Series"                   AS       "SHIPPING_NO_SERIES",
    "VAT Bus_ Posting Group"                AS       "VAT_BUS_POSTING_GROUP",
    "Prepayment Due Date"                   AS       "PREPAYMENT_DUE_DATE",
    "Prepmt_ Pmt_ Discount Date"            AS       "PREPMT_PMT_DISCOUNT_DATE",
    "Prepmt_ Payment Terms Code"            AS       "PREPMT_PAYMENT_TERMS_CODE",
    "Prepmt_ Payment Discount _"            AS       "PREPMT_PAYMENT_DISCOUNT",
    "Job Queue Entry ID"                    AS       "JOB_QUEUE_ENTRY_ID",
    "Dimension Set ID"                      AS       "DIMENSION_SET_ID",
    "Sell-to Contact No_"                   AS       "SELL_TO_CONTACT_NO",
    "Bill-to Contact No_"                   AS       "BILL_TO_CONTACT_NO",
    "Requested Delivery Date"               AS       "REQUESTED_DELIVERY_DATE",
    "Promised Delivery Date"                AS       "PROMISED_DELIVERY_DATE",
    "Shipping Time"                         AS       "SHIPPING_TIME",
    "Outbound Whse_ Handling Time"          AS       "OUTBOUND_WHSE_HANDLING_TIME",
    "Shipping Agent Service Code"           AS       "SHIPPING_AGENT_SERVICE_CODE",
    "load_timestamp"                        AS       "LOAD_TIMESTAMP",
    "source_system"                         AS       "SOURCE_SYSTEM "

from {{ source("raw", "nav9_nl_sales_header") }}
