{{ config(materialized="table") }}

select
    "timestamp"                                     ,
    "Document No_"          as ID                         ,
    "Line No_"                                      ,
    "Sell-to Customer No_"                          ,
    no_                                             ,
    "Location Code"                                 ,
    "Posting Group"                                 ,
    "Shipment Date"                                 ,
    description                                     ,
    "Unit of Measure"                               ,
    quantity                                        ,
    "Outstanding Quantity"                          ,
    "Qty_ to Invoice"                               ,
    "Qty_ to Ship"                                  ,
    "Unit Price"                                    ,
    "Unit Cost (LCY)"                               ,
    "VAT _"                                         ,
    "Line Discount _"                               ,
    "Line Discount Amount"                          ,
    amount                                          ,
    "Amount Including VAT"                          ,
    "Gross Weight"                                  ,
    "Net Weight"                                    ,
    "Unit Volume"                                   ,
    "Shortcut Dimension 1 Code"                     ,
    "Recalculate Invoice Disc_"                     ,
    "Outstanding Amount"                            ,
    "Qty_ Shipped Not Invoiced"                     ,
    "Shipped Not Invoiced"                          ,
    "Quantity Shipped"                              ,
    "Quantity Invoiced"                             ,
    "Profit _"                                      ,
    "Bill-to Customer No_"                          ,
    "Gen_ Bus_ Posting Group"                       ,
    "Gen_ Prod_ Posting Group"                      ,
    "VAT Calculation Type"                          ,
    "VAT Bus_ Posting Group"                        ,
    "VAT Prod_ Posting Group"                       ,
    "Currency Code"                                 ,
    "Outstanding Amount (LCY)"                      ,
    "Shipped Not Invoiced (LCY)"                    ,
    "VAT Base Amount"                               ,
    "Unit Cost"                                     ,
    "Line Amount"                                   ,
    "Dimension Set ID"                              ,
    "Returns Deferral Start Date"                   ,
    "Qty_ per Unit of Measure"                      ,
    planned                                         ,
    "Unit of Measure Code"                          ,
    "Quantity (Base)"                               ,
    "Outstanding Qty_ (Base)"                       ,
    "Qty_ to Invoice (Base)"                        ,
    "Qty_ to Ship (Base)"                           ,
    "Qty_ Shipped Not Invd_ (Base)"                 ,
    "Qty_ Shipped (Base)"                           ,
    "Qty_ Invoiced (Base)"                          ,
    "FA Posting Date"                               ,
    "Requested Delivery Date"                       ,
    "Promised Delivery Date"                        ,
    "Outbound Whse_ Handling Time"                  ,
    "Planned Delivery Date"                         ,
    "Planned Shipment Date"                         ,
    "Allow Item Charge Assignment"                  ,
    "Customer Disc_ Group"                          ,
    load_timestamp                                  ,
    source_system                                   

from {{ source("raw", "nav9_nl_sales_line") }}

