{{ config(materialized="table") }}

select
    "timestamp"                                     AS             "",
    "Document No_"                                  AS             "",
    "Line No_"                                      AS             "",
    "Sell-to Customer No_"                          AS             "",
    no_                                             AS             "",
    "Location Code"                                 AS             "",
    "Posting Group"                                 AS             "",
    "Shipment Date"                                 AS             "",
    description                                     AS             "",
    "Unit of Measure"                               AS             "",
    quantity                                        AS             "",
    "Outstanding Quantity"                          AS             "",
    "Qty_ to Invoice"                               AS             "",
    "Qty_ to Ship"                                  AS             "",
    "Unit Price"                                    AS             "",
    "Unit Cost (LCY)"                               AS             "",
    "VAT _"                                         AS             "",
    "Line Discount _"                               AS             "",
    "Line Discount Amount"                          AS             "",
    amount                                          AS             "",
    "Amount Including VAT"                          AS             "",
    "Gross Weight"                                  AS             "",
    "Net Weight"                                    AS             "",
    "Unit Volume"                                   AS             "",
    "Shortcut Dimension 1 Code"                     AS             "",
    "Recalculate Invoice Disc_"                     AS             "",
    "Outstanding Amount"                            AS             "",
    "Qty_ Shipped Not Invoiced"                     AS             "",
    "Shipped Not Invoiced"                          AS             "",
    "Quantity Shipped"                              AS             "",
    "Quantity Invoiced"                             AS             "",
    "Profit _"                                      AS             "",
    "Bill-to Customer No_"                          AS             "",
    "Gen_ Bus_ Posting Group"                       AS             "",
    "Gen_ Prod_ Posting Group"                      AS             "",
    "VAT Calculation Type"                          AS             "",
    "VAT Bus_ Posting Group"                        AS             "",
    "VAT Prod_ Posting Group"                       AS             "",
    "Currency Code"                                 AS             "",
    "Outstanding Amount (LCY)"                      AS             "",
    "Shipped Not Invoiced (LCY)"                    AS             "",
    "VAT Base Amount"                               AS             "",
    "Unit Cost"                                     AS             "",
    "Line Amount"                                   AS             "",
    "Dimension Set ID"                              AS             "",
    "Returns Deferral Start Date"                   AS             "",
    "Qty_ per Unit of Measure"                      AS             "",
    planned                                         AS             "",
    "Unit of Measure Code"                          AS             "",
    "Quantity (Base)"                               AS             "",
    "Outstanding Qty_ (Base)"                       AS             "",
    "Qty_ to Invoice (Base)"                        AS             "",
    "Qty_ to Ship (Base)"                           AS             "",
    "Qty_ Shipped Not Invd_ (Base)"                 AS             "",
    "Qty_ Shipped (Base)"                           AS             "",
    "Qty_ Invoiced (Base)"                          AS             "",
    "FA Posting Date"                               AS             "",
    "Requested Delivery Date"                       AS             "",
    "Promised Delivery Date"                        AS             "",
    "Outbound Whse_ Handling Time"                  AS             "",
    "Planned Delivery Date"                         AS             "",
    "Planned Shipment Date"                         AS             "",
    "Allow Item Charge Assignment"                  AS             "",
    "Customer Disc_ Group"                          AS             "",
    load_timestamp                                  AS             "",
    source_system                                   AS             ""

from {{ source("raw", "nav9_nl_sales_line") }}

