{{ config(materialized="table") }}

select
    "timestamp"                                         AS            "TIMESTAMP",
    "Document No_"                                      AS            "DOCUMENT_NO",
    "Line No_"                                          AS            "LINE_NO",
    "Sell-to Customer No_"                              AS            "SELL_TO_CUSTOMER_NO",
    "Type"                                              AS            "TYPE",
    no_                                                 AS            "NO",
    "Location Code"                                     AS            "LOCATION_CODE",
    "Posting Group"                                     AS            "POSTING_GROUP",
    "Shipment Date"                                     AS            "SHIPMENT_DATE",
    description                                         AS            "DESCRIPTION",
    "Unit of Measure"                                   AS            "UNIT_OF_MEASURE",
    quantity                                            AS            "QUANTITY",
    "Unit Price"                                        AS            "UNIT_PRICE",
    "Unit Cost (LCY)"                                   AS            "UNIT_COST_LCY",
    "VAT _"                                             AS            "VAT",
    "Line Discount Amount"                              AS            "LINE_DISCOUNT_AMOUNT",
    amount                                              AS            "AMOUNT",
    "Amount Including VAT"                              AS            "AMOUNT_INCLUDING_VAT",
    "Gross Weight"                                      AS            "GROSS_WEIGHT",
    "Net Weight"                                        AS            "NET_WEIGHT",
    "Unit Volume"                                       AS            "UNIT_VOLUME",
    "Shortcut Dimension 1 Code"                         AS            "SHORTCUT_DIMENSION_CODE",
    "Work Type Code"                                    AS            "WORK_TYPE_CODE",
    "Bill-to Customer No_"                              AS            "BILL_TO_CUSTOMER_NO",
    "Inv_ Discount Amount"                              AS            "INV_DISCOUNT_AMOUNT",
    "Gen_ Bus_ Posting Group"                           AS            "GEN_BUS_POSTING_GROUP",
    "Gen_ Prod_ Posting Group"                          AS            "GEN_PROD_POSTING_GROUP",
    "VAT Calculation Type"                              AS            "VAT_CALCULATION_TYPE",
    "VAT Bus_ Posting Group"                            AS            "VAT_BUS_POSTING_GROUP",
    "VAT Prod_ Posting Group"                           AS            "VAT_PROD_POSTING_GROUP",
    "VAT Base Amount"                                   AS            "VAT_BASE_AMOUNT",
    "Unit Cost"                                         AS            "UNIT_COST",
    "Line Amount"                                       AS            "LINE_AMOUNT",
    "VAT Identifier"                                    AS            "VAT_IDENTIFIER",
    "Posting Date"                                      AS            "POSTING_DATE",
    "Dimension Set ID"                                  AS            "DIMENSION_SET_ID",
    "Unit of Measure Code"                              AS            "UNIT_OF_MEASURE_CODE",
    "Quantity (Base)"                                   AS            "QUANTITY_BASE",
    "FA Posting Date"                                   AS            "FA_POSTING_DATE",
    "Responsibility Center"                             AS            "RESPONSIBILITY_CENTER",
    "Allow Line Disc_"                                  AS            "ALLOW_LINE_DISC",
    "Customer Disc_ Group"                              AS            "CUSTOMER_DISC_GROUP",
    load_timestamp                                      AS            "LOAD_TIMESTAMP",
    source_system                                       AS            "SOURCE_SYSTEM" 

from {{ source("raw", "nav9_nl_sales_invoice_line") }}
