{{ config(materialized="table") }}

select
    "timestamp",
    "Document No_",
    "Line No_",
    "Sell-to Customer No_",
    "Type",
    no_,
    "Location Code",
    "Posting Group",
    "Shipment Date",
    description,
    "Unit of Measure",
    quantity,
    "Unit Price",
    "Unit Cost (LCY)",
    "VAT _",
    "Line Discount _",
    "Line Discount Amount",
    amount,
    "Amount Including VAT",
    "Allow Invoice Disc_",
    "Gross Weight",
    "Net Weight",
    "Units per Parcel",
    "Unit Volume",
    "Appl_-to Item Entry",
    "Shortcut Dimension 1 Code",
    "Work Type Code",
    "Shipment No_",
    "Shipment Line No_",
    "Bill-to Customer No_",
    "Inv_ Discount Amount",
    "Drop Shipment",
    "Gen_ Bus_ Posting Group",
    "Gen_ Prod_ Posting Group",
    "VAT Calculation Type",
    "Transaction Type",
    "Transport Method",
    "Attached to Line No_",
    area,
    "Transaction Specification",
    "Tax Category",
    "Tax Area Code",
    "Tax Liable",
    "VAT Bus_ Posting Group",
    "VAT Prod_ Posting Group",
    "Blanket Order Line No_",
    "VAT Base Amount",
    "Unit Cost",
    "System-Created Entry",
    "Line Amount",
    "VAT Difference",
    "VAT Identifier",
    "IC Partner Ref_ Type",
    "Prepayment Line",
    "Posting Date",
    "Dimension Set ID",
    "Job Task No_",
    "Job Contract Entry No_",
    "Qty_ per Unit of Measure",
    "Unit of Measure Code",
    "Quantity (Base)",
    "FA Posting Date",
    "Depr_ until FA Posting Date",
    "Responsibility Center",
    "Cross-Reference No_",
    "Unit of Measure (Cross Ref_)",
    "Cross-Reference Type",
    "Cross-Reference Type No_",
    "Item Category Code",
    "Purchasing Code",
    "Product Group Code",
    "Appl_-from Item Entry",
    "Return Reason Code",
    "Allow Line Disc_",
    "Customer Disc_ Group",
    load_timestamp,
    source_system

from {{ source("raw", "nav9_nl_sales_invoice_line") }}
