{{ config(materialized="table") }}

select
    "timestamp",
    "Document No_",
    "Line No_",
    "Sell-to Customer No_",
    "Type",
    no_,
    "Location Code",
    "Posting Group",
    "Shipment Date",
    description,
    "Unit of Measure",
    quantity,
    "Unit Price",
    "Unit Cost (LCY)",
    "VAT _",
    "Line Discount Amount",
    amount,
    "Amount Including VAT",
    "Gross Weight",
    "Net Weight",
    "Unit Volume",
    "Shortcut Dimension 1 Code",
    "Work Type Code",
    "Bill-to Customer No_",
    "Inv_ Discount Amount",
    "Gen_ Bus_ Posting Group",
    "Gen_ Prod_ Posting Group",
    "VAT Calculation Type",
    "VAT Bus_ Posting Group",
    "VAT Prod_ Posting Group",
    "VAT Base Amount",
    "Unit Cost",
    "Line Amount",
    "VAT Identifier",
    "Posting Date",
    "Dimension Set ID",
    "Unit of Measure Code",
    "Quantity (Base)",
    "FA Posting Date",
    "Responsibility Center",
    "Allow Line Disc_",
    "Customer Disc_ Group",
    load_timestamp,
    source_system

from {{ source("raw", "nav9_nl_sales_invoice_line") }}
