{{ config(materialized="table") }}

select
    "timestamp",
    "Document Type",
    no_,
    "Sell-to Customer No_",
    "Bill-to Customer No_",
    "Bill-to Name",
    "Bill-to Address",
    "Bill-to City",
    "Bill-to Contact",
    "Ship-to Name",
    "Ship-to Address",
    "Ship-to City",
    "Ship-to Contact",
    "Order Date",
    "Posting Date",
    "Shipment Date",
    "Posting Description",
    "Payment Terms Code",
    "Due Date",
    "Payment Discount _",
    "Pmt_ Discount Date",
    "Shipment Method Code",
    "Location Code",
    "Shortcut Dimension 1 Code",
    "Shortcut Dimension 2 Code",
    "Customer Posting Group",
    "Currency Code",
    "Currency Factor",
    "Customer Price Group",
    "Prices Including VAT",
    "Invoice Disc_ Code",
    "Customer Disc_ Group",
    "Language Code",
    "Salesperson Code",
    "Order Class",
    "No_ Printed",
    "On Hold",
    "Applies-to Doc_ Type",
    "Applies-to Doc_ No_",
    "Bal_ Account No_",
    ship,
    invoice,
    "Print Posted Documents",
    "Shipping No_",
    "Posting No_",
    "Last Shipping No_",
    "Last Posting No_",
    "Prepayment No_",
    "Last Prepayment No_",
    "Prepmt_ Cr_ Memo No_",
    "Last Prepmt_ Cr_ Memo No_",
    "VAT Registration No_",
    "Combine Shipments",
    "Reason Code",
    "Gen_ Bus_ Posting Group",
    "EU 3-Party Trade",
    "Transaction Type",
    "Transport Method",
    "VAT Country_Region Code",
    "Sell-to Customer Name",
    "Sell-to Customer Name 2",
    "Sell-to Address",
    "Sell-to Address 2",
    "Sell-to City",
    "Sell-to Contact",
    "Bill-to Post Code",
    "Bill-to County",
    "Bill-to Country_Region Code",
    "Sell-to Post Code",
    "Sell-to County",
    "Sell-to Country_Region Code",
    "Ship-to Post Code",
    "Ship-to County",
    "Ship-to Country_Region Code",
    "Bal_ Account Type",
    "Exit Point",
    correction,
    "Document Date",
    "External Document No_",
    area,
    "Transaction Specification",
    "Payment Method Code",
    "Shipping Agent Code",
    "Package Tracking No_",
    "No_ Series",
    "Posting No_ Series",
    "Shipping No_ Series",
    "Tax Area Code",
    "Tax Liable",
    "VAT Bus_ Posting Group",
    reserve,
    "Applies-to ID",
    "VAT Base Discount _",
    status,
    "Invoice Discount Calculation",
    "Invoice Discount Value",
    "Send IC Document",
    "IC Status",
    "Sell-to IC Partner Code",
    "Bill-to IC Partner Code",
    "IC Direction",
    "Prepayment _",
    "Prepayment No_ Series",
    "Compress Prepayment",
    "Prepayment Due Date",
    "Prepmt_ Cr_ Memo No_ Series",
    "Prepmt_ Posting Description",
    "Prepmt_ Pmt_ Discount Date",
    "Prepmt_ Payment Terms Code",
    "Prepmt_ Payment Discount _",
    "Quote No_",
    "Job Queue Status",
    "Job Queue Entry ID",
    "Incoming Document Entry No_",
    "Dimension Set ID",
    "Authorization Required",
    "Credit Card No_",
    "Direct Debit Mandate ID",
    "Doc_ No_ Occurrence",
    "Campaign No_",
    "Sell-to Customer Template Code",
    "Sell-to Contact No_",
    "Bill-to Contact No_",
    "Bill-to Customer Template Code",
    "Opportunity No_",
    "Responsibility Center",
    "Shipping Advice",
    "Posting from Whse_ Ref_",
    "Requested Delivery Date",
    "Promised Delivery Date",
    "Shipping Time",
    "Outbound Whse_ Handling Time",
    "Shipping Agent Service Code",
    receive,
    "Return Receipt No_",
    "Return Receipt No_ Series",
    "Last Return Receipt No_",
    "Allow Line Disc_",
    "Get Shipment Used",
    "Assigned User ID",
    load_timestamp,
    source_system

from {{ source("raw", "nav9_nl_sales_header") }}
