{{ config(materialized="table") }}

select
    "timestamp",
    no_ AS "CUSTOMER ID",
    "Name",
    "Search Name",
    address,
    city,
    contact,
    "Territory Code",
    "Global Dimension 1 Code",
    "Credit Limit (LCY)",
    "Customer Posting Group",
    "Currency Code",
    "Language Code",
    "Payment Terms Code",
    "Fin_ Charge Terms Code",
    "Salesperson Code",
    "Shipment Method Code",
    "Shipping Agent Code",
    "Invoice Disc_ Code",
    "Customer Disc_ Group",
    "Country_Region Code",
    "Bill-to Customer No_",
    "Last Date Modified",
    "Location Code",
    "VAT Registration No_",
    "Gen_ Bus_ Posting Group",
    gln,
    "Post Code",
    "E-Mail",
    "Reminder Terms Code",
    "VAT Bus_ Posting Group",
    "IC Partner Code",
    "Responsibility Center",
    "Shipping Time",
    "Shipping Agent Service Code",
    "Service Zone Code",
    load_timestamp,
    source_system

from {{ source("raw", "nav9_sl_customer") }}
