{{ config(materialized="table") }}

select
    "timestamp",
    "Document Type",
    "Document No_",
    "Line No_",
    "Sell-to Customer No_",
    "Type",
    no_,
    "Location Code",
    "Posting Group",
    "Shipment Date",
    description,
    "Description 2",
    "Unit of Measure",
    quantity,
    "Outstanding Quantity",
    "Qty_ to Invoice",
    "Qty_ to Ship",
    "Unit Price",
    "Unit Cost (LCY)",
    "VAT _",
    "Line Discount _",
    "Line Discount Amount",
    amount,
    "Amount Including VAT",
    "Allow Invoice Disc_",
    "Gross Weight",
    "Net Weight",
    "Units per Parcel",
    "Unit Volume",
    "Appl_-to Item Entry",
    "Shortcut Dimension 1 Code",
    "Shortcut Dimension 2 Code",
    "Customer Price Group",
    "Job No_",
    "Work Type Code",
    "Recalculate Invoice Disc_",
    "Outstanding Amount",
    "Qty_ Shipped Not Invoiced",
    "Shipped Not Invoiced",
    "Quantity Shipped",
    "Quantity Invoiced",
    "Shipment No_",
    "Shipment Line No_",
    "Profit _",
    "Bill-to Customer No_",
    "Inv_ Discount Amount",
    "Purchase Order No_",
    "Purch_ Order Line No_",
    "Drop Shipment",
    "Gen_ Bus_ Posting Group",
    "Gen_ Prod_ Posting Group",
    "VAT Calculation Type",
    "Transaction Type",
    "Transport Method",
    "Attached to Line No_",
    "Exit Point",
    area,
    "Transaction Specification",
    "Tax Category",
    "Tax Area Code",
    "Tax Liable",
    "Tax Group Code",
    "VAT Clause Code",
    "VAT Bus_ Posting Group",
    "VAT Prod_ Posting Group",
    "Currency Code",
    "Outstanding Amount (LCY)",
    "Shipped Not Invoiced (LCY)",
    reserve,
    "Blanket Order No_",
    "Blanket Order Line No_",
    "VAT Base Amount",
    "Unit Cost",
    "System-Created Entry",
    "Line Amount",
    "VAT Difference",
    "Inv_ Disc_ Amount to Invoice",
    "VAT Identifier",
    "IC Partner Ref_ Type",
    "IC Partner Reference",
    "Prepayment _",
    "Prepmt_ Line Amount",
    "Prepmt_ Amt_ Inv_",
    "Prepmt_ Amt_ Incl_ VAT",
    "Prepayment Amount",
    "Prepmt_ VAT Base Amt_",
    "Prepayment VAT _",
    "Prepmt_ VAT Calc_ Type",
    "Prepayment VAT Identifier",
    "Prepayment Tax Area Code",
    "Prepayment Tax Liable",
    "Prepayment Tax Group Code",
    "Prepmt Amt to Deduct",
    "Prepmt Amt Deducted",
    "Prepayment Line",
    "Prepmt_ Amount Inv_ Incl_ VAT",
    "Prepmt_ Amount Inv_ (LCY)",
    "IC Partner Code",
    "Prepmt_ VAT Amount Inv_ (LCY)",
    "Prepayment VAT Difference",
    "Prepmt VAT Diff_ to Deduct",
    "Prepmt VAT Diff_ Deducted",
    "Dimension Set ID",
    "Qty_ to Assemble to Order",
    "Qty_ to Asm_ to Order (Base)",
    "Job Task No_",
    "Job Contract Entry No_",
    "Deferral Code",
    "Returns Deferral Start Date",
    "Variant Code",
    "Bin Code",
    "Qty_ per Unit of Measure",
    planned,
    "Unit of Measure Code",
    "Quantity (Base)",
    "Outstanding Qty_ (Base)",
    "Qty_ to Invoice (Base)",
    "Qty_ to Ship (Base)",
    "Qty_ Shipped Not Invd_ (Base)",
    "Qty_ Shipped (Base)",
    "Qty_ Invoiced (Base)",
    "FA Posting Date",
    "Depreciation Book Code",
    "Depr_ until FA Posting Date",
    "Duplicate in Depreciation Book",
    "Use Duplication List",
    "Responsibility Center",
    "Out-of-Stock Substitution",
    "Originally Ordered No_",
    "Originally Ordered Var_ Code",
    "Cross-Reference No_",
    "Unit of Measure (Cross Ref_)",
    "Cross-Reference Type",
    "Cross-Reference Type No_",
    "Item Category Code",
    nonstock,
    "Purchasing Code",
    "Product Group Code",
    "Special Order",
    "Special Order Purchase No_",
    "Special Order Purch_ Line No_",
    "Completely Shipped",
    "Requested Delivery Date",
    "Promised Delivery Date",
    "Shipping Time",
    "Outbound Whse_ Handling Time",
    "Planned Delivery Date",
    "Planned Shipment Date",
    "Shipping Agent Code",
    "Shipping Agent Service Code",
    "Allow Item Charge Assignment",
    "Return Qty_ to Receive",
    "Return Qty_ to Receive (Base)",
    "Return Qty_ Rcd_ Not Invd_",
    "Ret_ Qty_ Rcd_ Not Invd_(Base)",
    "Return Rcd_ Not Invd_",
    "Return Rcd_ Not Invd_ (LCY)",
    "Return Qty_ Received",
    "Return Qty_ Received (Base)",
    "Appl_-from Item Entry",
    "BOM Item No_",
    "Return Receipt No_",
    "Return Receipt Line No_",
    "Return Reason Code",
    "Copied From Posted Doc_",
    "Allow Line Disc_",
    "Customer Disc_ Group",
    load_timestamp,
    source_system

from {{ source("raw", "nav9_nl_sales_line") }}

