{{ config(materialized="table") }}

select
    timestamp_col,
    "No_",
    "Sell-to Customer No_",
    "Bill-to Customer No_",
    "Bill-to Name",
    "Bill-to Address",
    "Bill-to City",
    "Bill-to Contact",
    "Ship-to Name",
    "Ship-to Address",
    "Ship-to City",
    "Ship-to Contact",
    "Order Date",
    "Posting Date",
    "Shipment Date",
    "Posting Description",
    "Payment Terms Code",
    "Due Date",
    "Payment Discount _",
    "Pmt_ Discount Date",
    "Shipment Method Code",
    "Location Code",
    "Shortcut Dimension 1 Code",
    "Customer Posting Group",
    "Currency Code",
    "Currency Factor",
    "Invoice Disc_ Code",
    "Customer Disc_ Group",
    "Language Code",
    "Salesperson Code",
    "Order No_",
    "On Hold",
    "VAT Registration No_",
    "Gen_ Bus_ Posting Group",
    "EU 3-Party Trade",
    "VAT Country_Region Code",
    "Sell-to Customer Name",
    "Sell-to Address",
    "Sell-to City",
    "Sell-to Contact",
    "Bill-to Post Code",
    "Bill-to Country_Region Code",
    "Sell-to Post Code",
    "Sell-to Country_Region Code",
    "Ship-to Post Code",
    "Ship-to Country_Region Code",
    "Bal_ Account Type",
    "Correction",
    "Document Date",
    "Shipping Agent Code",
    "Package Tracking No_",
    "Pre-Assigned No_ Series",
    "No_ Series",
    "Order No_ Series",
    "Pre-Assigned No_",
    "User ID",
    "Source Code",
    "Tax Area Code",
    "Tax Liable",
    "VAT Bus_ Posting Group",
    "VAT Base Discount _",
    "Prepayment Invoice",
    "Dimension Set ID",
    "Document Exchange Status",
    "Coupled to CRM",
    "Cust_ Ledger Entry No_",
    "Sell-to Contact No_",
    "Bill-to Contact No_",
    "Responsibility Center",
    "Allow Line Disc_",
    "Get Shipment Used",
    load_timestamp,
    source_system

from {{ source("raw", "nav9_nl_sales_invoice_header") }}
